site_name: My Docs
#site_url: https://dstrest.github.io/mkdocs-example
theme:
  #name: material
  name: mkdocs-material-adr

  # Configuration for the material theme
  features:
    - navigation.instant

plugins:
  - mkdocs-material-adr/adr:
      graph_file: adr/index.md # index file for the ADRs
  - material/search # Note: all material plugin should be namespaced for them to work

nav:
  - Home: index.md
  - About: about.md
  - ADRs:
    - ADR Index: adr/index.md
    - ADR-0001 First: adr/0001-first.md
    - ADR-0002 Second: adr/0002-second.md
    - ADR-0003 Third: adr/0003-third.md
    - ADR-0004 Fourth: adr/0004-fourth.md
    - ADR-0005 Fifth: adr/0005-fifth.md
  - RFCs:
    - RFC Index: rfc/index.md
    - RFC-0001: rfc/0001-first.md
    - RFC-0002: rfc/0002-second.md
    - RFC-0003: rfc/0003-third.md

# ADR Extension Configuration
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format